const poj = require('./crawlers/poj')
const hdu = require('./crawlers/hdu')
const dashiye = require('./crawlers/dashiye')
const codeforces = require('./crawlers/codeforces')
const uva = require('./crawlers/uva')
const fzu = require('./crawlers/fzu')
const spoj = require('./crawlers/spoj')
const timus = require('./crawlers/timus')
const leetcode_cn = require('./crawlers/leetcode_cn')
const csu = require('./crawlers/csu')
const loj = require('./crawlers/loj')
const luogu = require('./crawlers/luogu')
const nowcoder = require('./crawlers/nowcoder')
const uestc = require('./crawlers/uestc')
const atcoder = require('./crawlers/atcoder')
const aizu = require('./crawlers/aizu')
const codechef = require('./crawlers/codechef')
const eljudge = require('./crawlers/eljudge')
const vjudge = require('./crawlers/vjudge')
/**
 * 返回 string映射所有爬虫函数的map
 * @returns {Promise<Map<any, any>>}
 */
module.exports = async function() {
  const crawlers_map = new Map()
  crawlers_map.set('poj', poj)
  crawlers_map.set('hdu', hdu)
  crawlers_map.set('dashiye', dashiye)
  crawlers_map.set('codeforces', codeforces)
  crawlers_map.set('uva', uva)
  crawlers_map.set('fzu', fzu)
  crawlers_map.set('spoj', spoj)
  crawlers_map.set('timus', timus)
  crawlers_map.set('leetcode_cn', leetcode_cn)
  crawlers_map.set('csu', csu)
  crawlers_map.set('loj', loj)
  crawlers_map.set('luogu', luogu)
  crawlers_map.set('nowcoder', nowcoder)
  crawlers_map.set('uestc', uestc)
  crawlers_map.set('atcoder', atcoder)
  crawlers_map.set('aizu', aizu)
  crawlers_map.set('codechef', codechef)
  crawlers_map.set('eljudge', eljudge)
  crawlers_map.set('vjudge', vjudge)
  return crawlers_map
}
